CREATE DATABASE CETRUS;
USE CETRUS;

CREATE TABLE ALUNO(
CODIGO INT auto_increment NOT NULL,
NOME VARCHAR(80) NOT NULL,
CPF VARCHAR(14) NOT NULL,
RG VARCHAR(9) NULL,
SEXO CHAR(1) NULL,
ENDERECO VARCHAR(80) NULL,
NUMERO INT NULL,
TELEFONE VARCHAR(20) NULL,
CELULAR VARCHAR(20) NULL,
EMAIL VARCHAR(80) NULL,
CEP VARCHAR(9) NULL,
BAIRRO VARCHAR(40) NULL,
CIDADE VARCHAR(40) NULL,
ESTADO VARCHAR(2) NULL,
PAIS VARCHAR(30) NULL,
OBSERVACAO VARCHAR(255) NULL,
DATA_CADASTRO DATETIME,

CONSTRAINT PK_ALUNO PRIMARY KEY(CODIGO)
);

CREATE TABLE PROFESSOR(
CODIGO INT auto_increment NOT NULL,
PROFESSOR VARCHAR(30) NULL,
EMAIL VARCHAR(80) NULL,

CONSTRAINT PK_PROFESSOR PRIMARY KEY(CODIGO)
);

CREATE TABLE CURSO(
CODIGO INT NOT NULL,
CURSO VARCHAR(80) NOT NULL,

CONSTRAINT PK_CURSO PRIMARY KEY(CODIGO)
);

CREATE TABLE TURMA(
CODIGO INT AUTO_INCREMENT NOT NULL,
DATA DATE,
TURMA VARCHAR(30) NOT NULL,
DURACAO VARCHAR(30) NULL,
CODIGO_PROFESSOR INT NOT NULL,
CODIGO_ALUNO INT NOT NULL,
CODIGO_CURSO INT NOT NULL,

CONSTRAINT PK_TURMA PRIMARY KEY(CODIGO),
CONSTRAINT FK_ALUNO FOREIGN KEY(CODIGO_ALUNO) REFERENCES ALUNO(CODIGO),
CONSTRAINT FK_PROFESSOR FOREIGN KEY(CODIGO_PROFESSOR) REFERENCES PROFESSOR(CODIGO),
CONSTRAINT FK_CURSO FOREIGN KEY(CODIGO_CURSO) REFERENCES CURSO(CODIGO)
);

CREATE VIEW ALUNOS_CURSANDOS
AS
SELECT A.CODIGO,A.NOME,C.CURSO,T.TURMA,T.DATA,T.DURACAO FROM ALUNO AS A
INNER JOIN TURMA AS T ON (A.CODIGO=T.CODIGO_ALUNO)
INNER JOIN CURSO AS C ON (C.CODIGO=T.CODIGO_CURSO);

CREATE TABLE HIST_ALT_ALUNO(
CODIGO INT,
DT_ALTERACAO DATETIME,
ALUNO_ANTIGO VARCHAR(80),
SEXO_ANTIGO CHAR(1),
EMAIL_ANTIGO VARCHAR(80),
OBSERVACAO_ANTIGO VARCHAR(255) 
);

DELIMITER $
CREATE TRIGGER HISTORICO_CLIENTE AFTER UPDATE ON ALUNO FOR EACH ROW BEGIN
IF NEW.NOME<>OLD.NOME THEN
INSERT INTO HIST_ALT_ALUNO (CODIGO,DT_ALTERACAO,ALUNO_ANTIGO,SEXO_ANTIGO,EMAIL_ANTIGO,OBSERVACAO_ANTIGO)
VALUES (NEW.CODIGO,NOW(),OLD.NOME,OLD.SEXO,OLD.EMAIL,OLD.OBSERVACAO);
END IF;
END $
DELIMITER ;
